### ISSUE TITLE
make_data() bug

### ISSUE THREAD

**Issue by acoppock** [egap/registration#11]
make_data() breaks if there are no covariates specified:

> po     <-  declare_potential_outcomes(
+   condition_names = c("Z0","Z1"),
+   outcome_formula = Y ~ .01 + 0*Z0 + .2*Z1
+ )
> 
> mock          <- make_data(potential_outcomes = po)
Show Traceback

Rerun with Debug
Error in parse(text = x, keep.source = FALSE) : 
 <text>:2:0: unexpected end of input
1: Y ~ 
  ^

**Comment by jaspercooper** [comment]
Thanks for pointing this out, it's now been fixed. 

Now, if you give make_data() an outcomes_object with no covariates, it will use the information you give it about the DGP of the outcome variable to create a temporarily-stored "untreated_outcome" to which the treatment conditions in the outcome_formula are added. If you tell it that your outcome variable is N(10,5), then the untreated outcome is distributed normally with mean 10 and sd 5. If you tell it nothing then it defaults to N(0,1). And finally, if you tell it that the outcome variable's DGP is binomial, it defaults to a latent N(0,1) to which the treatment effects are added as log odds changes and it is transformed back into probabilities through the inverse logit and from there into 0s and 1s.
