### ISSUE TITLE
get_power should be able to resample only potential_outcomes

### ISSUE THREAD

**Issue by graemeblair** [egap/registration#14]
in addition to resampling both data and potential_outcomes, it should be able to just resample potential_outcomes given a fixed dataset.

**Comment by jaspercooper** [comment]
I can try to implement something like this. What were you thinking of as
the stochastic component here?

**Comment by graemeblair** [comment]
It's all set up already essentially in get_power, the only thing that's missing (which you could definitely do, thanks) is to set up make_data so that it took either a covariates object from declare_covariates or a data frame. Then I can straightforwardly either send make_data the covariates or a data frame depending on what the user puts in. Does that solution work? 

We already set up the resampling in get_power() for when the user sends a covariates object and a potential_outcomes object.

**Comment by jaspercooper** [comment]
Right now make_data() should be able to handle dataframe + outcomes_object, is it breaking when you try to do this?

**Comment by graemeblair** [comment]
Oh, my bad. I will try that.

**Comment by graemeblair** [comment]
Changes to fix this in commit a3dec1b9445150ae2a12f9137611b48e72f44e99
