### ISSUE TITLE
harmonize declare_* and make_*

### ISSUE THREAD

**Issue by acoppock** [egap/registration#2]
Proposal:

something like

cov_object <- declare_covariates()
po_object <- declare_potential_outcomes()

data <- make_data(cov_object, po_object)

this way it'll be easy to "sample from population" as well as work with a static dataframe

this should probably be addressed after v0.1 is working

**Comment by jaspercooper** [comment]
This is very nice, I like how clear it is. It's a small step to implement in version 0.1

**Comment by jaspercooper** [comment]
This is now implemented.
