### ISSUE TITLE
make declare_clusters function

### ISSUE THREAD

**Issue by graemeblair** [egap/registration#20]
This function returns a function that will, given a data frame of covariates, return a set of "somewhat sensible" clusters. Usually this will declare a variable name to be a cluster variable.

Will need to be added to make_data.

**Comment by macartan** [comment]
Does it include a facility to make sure clusters are within  blocks, if
these exist

**Comment by graemeblair** [comment]
It will now. Thanks. Clusters if declared will have to be declared first in
the workflow.

**Comment by graemeblair** [comment]
This all works!
