### ISSUE TITLE
Modify declare_analysis

### ISSUE THREAD

**Issue by graemeblair** [egap/registration#23]
Analysis will take formula, method, and a quantity_of_interest function

Quantity of interest function that it declares extracts SATE^\hat and se.SATE^\hat from a run analysis and extracts SATE from a data frame with potential_outcomes in it.

It somehow needs to extract the *same* quantity of interest from both run analysis and potential_outcomes.

**Comment by graemeblair** [comment]
To move the discussion forward from Macartan's e-mail, my proposal for declare_analysis(), which is slightly different than the code you wrote Macartan, is:

declare_analysis(formula = Y ~ Z, treatment_variable = "Z", method = method.function.default, estimates.function = estimates.function.default, estimand.function = estimand.function.default)

The difference is this separates the model function (method.function) from the estimates function, so the user can still access the actual model fit as well as the estimates.

By default, we will (try to) code it to infer the estimate and the estimand implied by the formula and method function, so typically the user will just supply formula, treatment_variable, and method = "lm" / "glm" / whatever.

There would be three wrapper functions used for different purposes: run_analysis which just runs the analysis; get_estimates (which extracts estimates from a run_analysis output, or runs analysis and then does that); and get_estimands (which extracts estimands from a data frame).

**Comment by graemeblair** [comment]
From another issue, the estimates_function will return a vector with (estimate, se.estimate, confidence interval).

**Comment by graemeblair** [comment]
We also probably want a p-value in that vector so we don't have to carry around df.

**Comment by macartan** [comment]
Yes to p value; and perhaps n if we want standardized minimal tales

Important I think to allow this to be set up to return result for multiple
models. In the one I jimmied up the results of estimates was a matrix with
one column per estimate and a row for each of the stats. Think that is
handy and can later be converted into the full row-per-iteration format.

Guessing at the implied estimand sounds hard to me unless we basically take
the estimand to be whatever the estimate estimates. That's OK but we lose
the ability to identify errors in a general way. Worthwhile though to get
it off the ground  for low investment users.

**Comment by graemeblair** [comment]
All implemented! see declare_analysis(), get_estimates(), get_estimands(), get_estimates_model(), get_estimands_model(), truth_data_frame(), and simulate_experiment(). See commit 26ceb47e33102725b8eda6ca12832f6f55e8a280
