### ISSUE TITLE
new function permutation_matrix() 

### ISSUE THREAD

**Issue by graemeblair** [egap/registration#28]
Creates a permutation matrix based on a design object and a realized set of covariates and potential outcomes, so that the user could do RI in their analyses.

**Comment by macartan** [comment]
to be clear: treatment assignments get shuffled according to randomization
scheme, but POs and Xs do not. or are POs part of this at all? For actual
RI analyses (other than for sharp null) POs wll have to be guessed at by
users as a function of Y and a model.

**Comment by graemeblair** [comment]
Sorry, typing faster than thinking - the permutation_matrix takes a design object and a (realized) data object (which it only uses to know which units are in which cluster/block, etc., so the random assignment is in the proper order).

**Comment by acoppock** [comment]
make_permutation_matrix() is now in reveal_design.r

It takes a fixed dataset, then makes permutations according to design.

One feature that could be implemented in the future is figuring out if these are ALL of the possible assignments or just a sample.  a la the ri package somehow.
