### ISSUE TITLE
What is power power of

### ISSUE THREAD

**Issue by macartan** [egap/registration#33]
Because of user control over the exact estimands as well as the complexity of the dgp (POs depending on Xs) it may no longer be simple to interpret power since power always depends on a presumption of some actual effect. Our estimate of b from the get_qois function (or whatever) may be our friend here: for each qoi we have an empirical estimate of the population level estimand and so power for a particular analysis should be provided as a function of that. All the more reason to specify the estimand.  So implication: calculate E(b) and report it alongside power for each power result.

**Comment by graemeblair** [comment]
PATE is now returned in the summary(simulate_experiment(...)) output. See commit 26ceb47e33102725b8eda6ca12832f6f55e8a280
