### ISSUE TITLE
ra_fun() should accept arguments so for multiple power analyses

### ISSUE THREAD

**Issue by graemeblair** [egap/registration#8]
To run a power analysis on same declared design and analysis but for varying values of a parameter like N, need to modify ra_fun() to accept arguments such as N. Or another solution to allow running a power analysis with different parameter values.

**Comment by acoppock** [comment]
Prefer to handle power simulations by specifying a series of design declarations/and or changes to dgp. We'll need to think of a nice way to do common ones, like varying N.
